using System;

namespace TextMonster.Xml.Xml_Reader
{
  internal class XmlBooleanConverter : XmlBaseConverter
  {
    protected XmlBooleanConverter(XmlSchemaType schemaType)
      : base(schemaType)
    {
    }

    public static XmlValueConverter Create(XmlSchemaType schemaType)
    {
      return new XmlBooleanConverter(schemaType);
    }

    #region AUTOGENERATED_XMLBOOLEANCONVERTER

    //-----------------------------------------------
    // ToBoolean
    //-----------------------------------------------

    public override bool ToBoolean(string value)
    {
      if (value == null) throw new ArgumentNullException("value");

      return XmlConvert.ToBoolean((string)value);
    }
    public override bool ToBoolean(object value)
    {
      if (value == null) throw new ArgumentNullException("value");

      Type sourceType = value.GetType();

      if (sourceType == BooleanType) return ((bool)value);
      if (sourceType == StringType) return XmlConvert.ToBoolean((string)value);
      if (sourceType == XmlAtomicValueType) return ((XmlAtomicValue)value).ValueAsBoolean;

      return (bool)ChangeListType(value, BooleanType, null);
    }


    //-----------------------------------------------
    // ToDateTime
    //-----------------------------------------------

    // This converter does not support conversions to DateTime.


    //-----------------------------------------------
    // ToDecimal
    //-----------------------------------------------

    // This converter does not support conversions to Decimal.


    //-----------------------------------------------
    // ToDouble
    //-----------------------------------------------

    // This converter does not support conversions to Double.


    //-----------------------------------------------
    // ToInt32
    //-----------------------------------------------

    // This converter does not support conversions to Int32.


    //-----------------------------------------------
    // ToInt64
    //-----------------------------------------------

    // This converter does not support conversions to Int64.


    //-----------------------------------------------
    // ToSingle
    //-----------------------------------------------

    // This converter does not support conversions to Single.


    //-----------------------------------------------
    // ToString
    //-----------------------------------------------

    public override string ToString(bool value)
    {
      return XmlConvert.ToString((bool)value);
    }

    public override string ToString(object value, IXmlNamespaceResolver nsResolver)
    {
      if (value == null) throw new ArgumentNullException("value");

      Type sourceType = value.GetType();

      if (sourceType == BooleanType) return XmlConvert.ToString((bool)value);
      if (sourceType == StringType) return ((string)value);
      if (sourceType == XmlAtomicValueType) return ((XmlAtomicValue)value).Value;

      return (string)ChangeListType(value, StringType, nsResolver);
    }


    //-----------------------------------------------
    // ChangeType
    //-----------------------------------------------

    public override object ChangeType(bool value, Type destinationType)
    {
      if (destinationType == null) throw new ArgumentNullException("destinationType");

      if (destinationType == ObjectType) destinationType = DefaultClrType;
      if (destinationType == BooleanType) return ((bool)value);
      if (destinationType == StringType) return XmlConvert.ToString((bool)value);
      if (destinationType == XmlAtomicValueType) return (new XmlAtomicValue(SchemaType, (bool)value));
      if (destinationType == XPathItemType) return (new XmlAtomicValue(SchemaType, (bool)value));

      return ChangeListType(value, destinationType, null);
    }

    public override object ChangeType(string value, Type destinationType, IXmlNamespaceResolver nsResolver)
    {
      if (value == null) throw new ArgumentNullException("value");
      if (destinationType == null) throw new ArgumentNullException("destinationType");

      if (destinationType == ObjectType) destinationType = DefaultClrType;
      if (destinationType == BooleanType) return XmlConvert.ToBoolean((string)value);
      if (destinationType == StringType) return ((string)value);
      if (destinationType == XmlAtomicValueType) return (new XmlAtomicValue(SchemaType, (string)value));
      if (destinationType == XPathItemType) return (new XmlAtomicValue(SchemaType, (string)value));

      return ChangeListType(value, destinationType, nsResolver);
    }

    public override object ChangeType(object value, Type destinationType, IXmlNamespaceResolver nsResolver)
    {
      if (value == null) throw new ArgumentNullException("value");
      if (destinationType == null) throw new ArgumentNullException("destinationType");

      Type sourceType = value.GetType();

      if (destinationType == ObjectType) destinationType = DefaultClrType;
      if (destinationType == BooleanType) return this.ToBoolean(value);
      if (destinationType == StringType) return this.ToString(value, nsResolver);
      if (destinationType == XmlAtomicValueType)
      {
        if (sourceType == BooleanType) return (new XmlAtomicValue(SchemaType, (bool)value));
        if (sourceType == StringType) return (new XmlAtomicValue(SchemaType, (string)value));
        if (sourceType == XmlAtomicValueType) return ((XmlAtomicValue)value);
      }
      if (destinationType == XPathItemType)
      {
        if (sourceType == BooleanType) return (new XmlAtomicValue(SchemaType, (bool)value));
        if (sourceType == StringType) return (new XmlAtomicValue(SchemaType, (string)value));
        if (sourceType == XmlAtomicValueType) return ((XmlAtomicValue)value);
      }

      return ChangeListType(value, destinationType, nsResolver);
    }
    #endregion
  }
}
